apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  labels:
    app: cs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cs
  template:
    metadata:
      labels:
        app: cs
    spec:
      containers:
        - name: client-service
          image: test-server
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"