apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: web-servers
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-service
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: client-service
        minAllowed:
          cpu: "1000m"
          memory: "1Gi"
        maxAllowed:
          cpu: "2000m"
          memory: "2Gi"